CREATE VIEW trabajadores
AS
	SELECT ISNULL(EMP_NO, 0) AS ID, APELLIDO, OFICIO AS TRABAJO, SALARIO
		FROM EMP
	UNION
	SELECT DOCTOR_NO, APELLIDO, ESPECIALIDAD, SALARIO
		FROM DOCTOR
	UNION
	SELECT EMPLEADO_NO, APELLIDO, FUNCION, SALARIO
		FROM PLANTILLA
GO

CREATE VIEW trabajadorespaginacion
AS
	SELECT
	CAST(ISNULL(ROW_NUMBER() OVER (ORDER BY ID), 0) AS INT) AS POSICION
	, trabajadores.* FROM trabajadores
GO

SELECT * FROM trabajadorespaginacion WHERE SALARIO >= 200000

SELECT * FROM trabajadores
SELECT * FROM EMP
SELECT * FROM DOCTOR
SELECT * FROM PLANTILLA


CREATE PROCEDURE paginargrupotrabajadores
(@POSICION INT, @REGISTROS INT OUT)
AS
    SELECT @REGISTROS = COUNT(ID) FROM trabajadorespaginacion
	SELECT ID, APELLIDO, TRABAJO, SALARIO FROM trabajadorespaginacion
	WHERE POSICION >= @POSICION AND POSICION < (@POSICION + 4)
GO

ALTER PROCEDURE paginargrupotrabajadoressalario
(@POSICION INT, @SALARIO INT, @REGISTROS INT OUT)
AS
	SELECT @REGISTROS = COUNT(ID) FROM trabajadores
		WHERE SALARIO >= @SALARIO
	DECLARE @POSICIONTABLA INT
	SELECT @POSICIONTABLA =
		CAST(ISNULL(ROW_NUMBER() OVER (ORDER BY SALARIO), 0) AS INT) FROM trabajadores
	SELECT @POSICIONTABLA AS POSICION
	, trabajadores.* FROM trabajadores
	WHERE SALARIO >= 300000 
	AND @POSICIONTABLA >= 1
	AND @POSICIONTABLA < (1 + 3)
GO